spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_management_system
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
jwt:
 secret:
  access: abcdefghijklmnOPQRSTUVWXYZfdwfsdfsoldfmsdmfnoadfhwoijdfasodfjmochlfkjlsdfxjdghsdfjksodfl
#server:
#  error:
#    include-stacktrace: never
application-description: description api artur
application-version: v1

